name: plugins_list
description: A tool to fetch and manage Flutter/Dart package dependencies and their versions by scanning pubspec.yaml files.
version: 1.0.2
homepage: https://github.com/hrajwade96/flutter_plugins_list

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  glob: ^2.0.1
  http: ^1.2.1
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  flutter_plugins_list: flutter_plugins_list