name: plugins_list
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  glob: ^2.0.1
  http: ^0.13.3
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  flutter_plugins_list: flutter_plugins_list